<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>ee28b0fb-2ee5-4b48-a0ef-d84288b63bed</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="Mediator.SourceGenerator" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../infrastructure/persistence/sql/GoActive.Infrastructure.Storage.Geo/GoActive.Infrastructure.Storage.Geo.csproj" />
    <ProjectReference Include="..\..\modules\geo\GoActive.Modules.Geo.Application\GoActive.Modules.Geo.Application.csproj" />
  </ItemGroup>

</Project>