// <auto-generated />
using System;
using GoActive.Infrastructure.Storage.Geo;
using GoActive.Shared.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoActive.Infrastructure.Storage.Geo.Migrations.Migrations
{
    [DbContext(typeof(GeoContext))]
    [Migration("20250615171049_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gin");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoActive.Infrastructure.Storage.Geo.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Building")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("building");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("district");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("character varying(31)")
                        .HasColumnName("external_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point)")
                        .HasColumnName("location");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("region");

                    b.Property<string>("Settlement")
                        .HasMaxLength(82)
                        .HasColumnType("character varying(82)")
                        .HasColumnName("settlement");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Street")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("street");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("Country")
                        .HasDatabaseName("ix_addresses_country");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_addresses_source_external_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("GoActive.Infrastructure.Storage.Geo.Entities.Spot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Activities")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("activities");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<float?>("Altitude")
                        .HasColumnType("real")
                        .HasColumnName("altitude");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_spots");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_spots_address_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_spots_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NormalizedTitle", "Location")
                        .IsUnique()
                        .HasDatabaseName("ix_spots_normalized_title_location");

                    b.ToTable("spots", (string)null);
                });

            modelBuilder.Entity("GoActive.Infrastructure.Storage.Geo.Entities.Spot", b =>
                {
                    b.HasOne("GoActive.Infrastructure.Storage.Geo.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .HasConstraintName("fk_spots_addresses_address_id");

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
